version: "3.9"
services:
  database:
    image: postgres:13.1-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123456
    volumes:
      - ./dbInitScripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

#  identity:
#    image: quay.io/keycloak/keycloak:12.0.1
#    ports:
#      - 9990:9990
#      - 8556:8080
#    environment:
#      KEYCLOAK_USER: keycloak
#      KEYCLOAK_PASSWORD: 123456

  hasura:
    image: hasura/graphql-engine:v1.3.3
    ports:
      - 8080:8080
    restart: always
    depends_on:
      database:
        condition: service_healthy
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:123456@database:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"